## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - OPENEBS-SETUP
  - FUNCTIONAL
  - CHAOS
  - CLEANUP

BFDT-OpenShift-3.10:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP
  script:     
    - chmod 755 ./Openshift-EE/pipelines/kafka/stages/1-cluster-setup/BFDT-cluster-setup/cluster-state
    - ./Openshift-EE/pipelines/kafka/stages/1-cluster-setup/BFDT-cluster-setup/cluster-state

9FWN-OpenEBS:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/2-setup/9FWN-openebs-deploy/deploy-openebs
    - ./Openshift-EE/pipelines/kafka/stages/2-setup/9FWN-openebs-deploy/deploy-openebs

      #PHK2-OpenEBS-POLICIES:
      #  image: openebs/openshift-ci:latest
      #  stage: OPENEBS-SETUP
      #  script:
      #    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/2-setup/PHK2-storage-policies/openebs-sc
      #    - ./Openshift-EE/pipelines/kafka/stages/2-setup/PHK2-storage-policies/openebs-sc
  
IGVJ-CSTOR-POOL:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/2-setup/IGVJ-create-striped-pool/create-pool
    - ./Openshift-EE/pipelines/kafka/stages/2-setup/IGVJ-create-striped-pool/create-pool
    
.func_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  when: always
  dependencies:
    - 9FWN-OpenEBS
     
JCXF-Kafka-Provision:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/3-functional/JCXF-kafka-provision/kafka-provision
    - ./Openshift-EE/pipelines/kafka/stages/3-functional/JCXF-kafka-provision/kafka-provision

.chaos_test_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  when: always
  dependencies:
    - 9FWN-OpenEBS

1Q3O-Zookeeper-App-scaleup:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/1Q3O-zookeeper-app-scaleup/zookeeper-app-scaleup
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/1Q3O-zookeeper-app-scaleup/zookeeper-app-scaleup

9GL2-Kafka-App-scaleup:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/9GL2-kafka-app-scaleup/kafka-app-scaleup
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/9GL2-kafka-app-scaleup/kafka-app-scaleup

28TT-Kafka-App-Kill:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/28TT-kafka-app-kill/kafka-app-kill
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/28TT-kafka-app-kill/kafka-app-kill

I8TT-cstor-target-kill:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/I8TT-cstor-target-kill/cstor-target-kill
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/I8TT-cstor-target-kill/cstor-target-kill

JGJD-cstor-target-network-delay:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/JGJD-cstor-target-network-delay/cstor-target-network-delay
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/JGJD-cstor-target-network-delay/cstor-target-network-delay

LTSR-kafka-broker-network-delay:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/LTSR-kafka-broker-network-delay/kafka-broker-network-delay
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/LTSR-kafka-broker-network-delay/kafka-broker-network-delay

NU74-cstor-pool-delete:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/NU74-cstor-pool-delete/cstor-pool-delete
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/NU74-cstor-pool-delete/cstor-pool-delete

WNCK-zookeeper-app-kill:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/WNCK-zookeeper-app-kill/zookeeper-app-kill
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/WNCK-zookeeper-app-kill/zookeeper-app-kill    

ZU3E-cstor-pool-kill:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/4-chaos/ZU3E-cstor-pool-kill/cstor-pool-kill
    - ./Openshift-EE/pipelines/kafka/stages/4-chaos/ZU3E-cstor-pool-kill/cstor-pool-kill

      #GP95-openebs-Uninstall:
      #  image: openebs/openshift-ci:latest
      #  stage: CLEANUP
      #  when: always
      #  dependencies:
      #    - 9FWN-OpenEBS
      #  script:
      #    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/5-cleanup/GP95-openebs-cleanup/openebs-cleanup
      #    - ./Openshift-EE/pipelines/kafka/stages/5-cleanup/GP95-openebs-cleanup/openebs-cleanup

U0AX-cluster-Delete:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  dependencies:
    - BFDT-OpenShift-3.10
  script:
    - chmod 775 ./Openshift-EE/pipelines/kafka/stages/5-cleanup/U0AX-cluster-cleanup/cluster-cleanup
    - ./Openshift-EE/pipelines/kafka/stages/5-cleanup/U0AX-cluster-cleanup/cluster-cleanup
